version: "3.9"

services:
  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: snippetflow_db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://your_user:your_password@db:5432/snippetflow_db
      # Other environment variables your backend needs

volumes:
  db_data:
